global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "mlops_api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
